name: 'on_pull_request'
on:
  - pull_request

jobs:
  lint:
    name: 'tflint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Setup python'
        uses: actions/setup-python@v2
        with:
            python-version: '3.x'
      - name: 'install tflint'
        run: |
          curl -L "$(curl -Ls https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E "https://.+?_linux_amd64.zip")" -o tflint.zip && unzip -o tflint.zip && rm tflint.zip
      - name: 'run tflint'
        run: |
          ./tflint
